name: wardaya
description: "A Wardaya e-commerce application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI packages
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17 
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  skeletonizer: ^1.4.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  lottie: ^3.3.1
  flutter_styled_toast: ^2.2.1
  cached_network_image: ^3.3.0
  
  # State management
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  provider: ^6.1.4
  
  # Network & API
  dio: ^5.8.0+1
  dio_smart_retry: ^6.0.0
  dio_web_adapter: ^2.1.1
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.2
  http: ^1.1.0
  webview_flutter: 4.2.2
  webview_flutter_android: 3.9.3
  webview_flutter_wkwebview: 3.7.3
  
  # Local storage
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  
  # DI
  get_it: ^7.7.0
  
  # Localization
  easy_localization: ^3.0.7+1
  localization:
    path: ./localization
    
  # Maps & Location
  google_maps_flutter: ^2.6.0
  geolocator: ^11.0.0
  country_picker: ^2.0.25
  flutter_contacts: ^1.1.7+1
  
  # Environment config
  flutter_dotenv: ^5.1.0
  
  # Utility packages
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  intl: ^0.19.0
  logger: ^2.5.0

  # Other functionality
  benefit_pay_flutter: ^1.0.1
  crypto: ^3.0.3
  camera: ^0.10.6
  signature: ^5.5.0
  flutter_signature_pad: ^3.0.1
  qr_flutter: ^4.1.0
  mobkit_dashed_border: ^0.0.5
  custom_loading: ^0.0.1
  flutter_debouncer: ^2.0.0
  
  # Forms and input
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^10.0.1
  country_code_picker: ^3.0.0
  
  # Authentication
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^5.0.0
  
  # Code generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  infinite_scroll_pagination: ^5.0.0
  share_plus: ^10.1.4
  oktoast: ^3.4.0
  app_links: ^3.4.3  # Replacing uni_links (discontinued)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.15
  retrofit_generator: ^8.2.1
  json_serializable: ^6.9.0
  freezed: ^2.5.7
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.4
  flutter_flavor: ^3.1.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/logo/
    - assets/images/cards/
    - assets/images/categories/
    - assets/lottie/
    - assets/svgs/
    - assets/pay_cards/
    - assets/i18n/
    - .env
    
  fonts:
    - family: Kammerlander
      fonts:
        - asset: assets/fonts/Kammerlander-Regular.ttf
          weight: 400
        - asset: assets/fonts/Kammerlander-Bold.ttf
          weight: 700
    - family: WardayaIcons
      fonts:
        - asset: assets/fonts/WardayaIcons.ttf
