name: wardaya
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  build_runner: ^2.4.7
  cached_network_image: ^3.3.1
  cool_dropdown: ^2.1.0
  cupertino_icons: ^1.0.6
  dio: ^5.3.3
  dio_smart_retry: ^6.0.0
  dropdown_button2: ^2.3.9
  dropdown_search: ^5.0.6
  easy_localization: ^3.0.3
  firebase_core: ^2.25.0
  firebase_auth: ^4.12.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.9
  flutter_translate: ^4.0.4
  font_awesome_flutter: ^10.8.0
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  intl: ^0.19.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  logger: ^2.4.0
  lottie: ^3.1.2
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.4
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  toggle_switch: ^2.3.0
  url_launcher: ^6.2.6
  typewritertext: ^3.0.9
  auto_size_text: ^3.0.0
  flutter_flavor: ^3.1.3
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.2.0+3
  mobkit_dashed_border: ^0.0.7
  
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo/
    - assets/images/cards/
    - assets/images/categories/
    - assets/pay_cards/
    - assets/lottie/
    - assets/svgs/
    
  fonts:
    - family: Kammerlander
      fonts:
        - asset: assets/fonts/Kammerlander-Bold.ttf
        - asset: assets/fonts/Kammerlander-Regular.ttf
    - family: WardayaIcons 
      fonts:
        - asset: assets/fonts/WardayaIcons.ttf  