// Generated by Flutter Assets

// ignore_for_file: unused_field, camel_case_types, non_constant_identifier_names, library_private_types_in_public_api

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
        
class Assets extends StatelessWidget {
  final AssetsData assets;
  final Widget child;

  const Assets({
    super.key,
    required this.assets,
    required this.child,
  });

  static AssetsData of(BuildContext context) {
    final widget = context.dependOnInheritedWidgetOfExactType<_InheritedAssets>();
    return widget?.assets ?? AssetsData.light();
  }

  @override
  Widget build(BuildContext context) {
    return _InheritedAssets(
      assets: assets,
      child: child,
    );
  }
}

class _InheritedAssets extends InheritedWidget {
  final AssetsData assets;

  const _InheritedAssets({
    required this.assets,
    required super.child,
  });

  @override
  bool updateShouldNotify(covariant _InheritedAssets oldWidget) => assets != oldWidget.assets;
}

class AssetsData {
  static AssetsData? _light;
  static AssetsData? _dark;

  factory AssetsData.light() => _light ??= AssetsData._(brightness: Brightness.light);
  factory AssetsData.dark() => _dark ??= AssetsData._(brightness: Brightness.dark);
  factory AssetsData.brightness(Brightness brightness) => brightness == Brightness.light ? AssetsData.light() : AssetsData.dark();

  final Brightness _brightness;

  AssetsData._({
    required Brightness brightness,
  })  : _brightness = brightness,
        fonts = _assets_fonts_dart._(brightness: brightness),
        i18n = _assets_i18n_dart._(brightness: brightness),
        images = _assets_images_dart._(brightness: brightness),
        lottie = _assets_lottie_dart._(brightness: brightness),
        pay_cards = _assets_pay_cards_dart._(brightness: brightness),
        svgs = _assets_svgs_dart._(brightness: brightness);

  final _assets_fonts_dart fonts;
  final _assets_i18n_dart i18n;
  final _assets_images_dart images;
  final _assets_lottie_dart lottie;
  final _assets_pay_cards_dart pay_cards;
  final _assets_svgs_dart svgs;
}

class _assets_fonts_dart {
  final Brightness _brightness;

  _assets_fonts_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final Kammerlander_Bold_ttf = 'assets/fonts/Kammerlander-Bold.ttf';
  final Kammerlander_Regular_ttf = 'assets/fonts/Kammerlander-Regular.ttf';
  final WardayaIcons_ttf = 'assets/fonts/WardayaIcons.ttf';
}

class _assets_i18n_dart {
  final Brightness _brightness;

  _assets_i18n_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final ar_yaml = 'assets/i18n/ar.yaml';
  final en_yaml = 'assets/i18n/en.yaml';
}

class _assets_images_dart {
  final Brightness _brightness;

  _assets_images_dart._({
    required Brightness brightness,
  })  : _brightness = brightness,
        cards = _assets_images_cards_dart._(brightness: brightness),
        categories = _assets_images_categories_dart._(brightness: brightness),
        logo = _assets_images_logo_dart._(brightness: brightness);

  final _assets_images_cards_dart cards;
  final _assets_images_categories_dart categories;
  final _assets_images_logo_dart logo;

  final anniversary_png = 'assets/images/anniversary.png';
  final ballones_png = 'assets/images/ballones.png';
  final cake_png = 'assets/images/cake.png';
  final chocolate_png = 'assets/images/chocolate.png';
  final delivery_png = 'assets/images/delivery.png';
  final flower_gift_png = 'assets/images/flower_gift.png';
  final flowers_png = 'assets/images/flowers.png';
  final flowersAndGifts_png = 'assets/images/flowersAndGifts.png';
  final flowersAndPlants_png = 'assets/images/flowersAndPlants.png';
  final flowers_gifts_png = 'assets/images/flowers_gifts.png';
  final jewlary_png = 'assets/images/jewlary.png';
  final ring_png = 'assets/images/ring.png';
  final sub1_png = 'assets/images/sub1.png';
  final sub2_png = 'assets/images/sub2.png';
  final sub3_png = 'assets/images/sub3.png';
  final subscription_png = 'assets/images/subscription.png';
  final subscriptions_banner_png = 'assets/images/subscriptions_banner.png';
  final teddy_png = 'assets/images/teddy.png';
}

class _assets_images_cards_dart {
  final Brightness _brightness;

  _assets_images_cards_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final card1_png = 'assets/images/cards/card1.png';
  final card2_png = 'assets/images/cards/card2.png';
  final empty_card_png = 'assets/images/cards/empty_card.png';
}

class _assets_images_categories_dart {
  final Brightness _brightness;

  _assets_images_categories_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final aunt_png = 'assets/images/categories/aunt.png';
  final children_png = 'assets/images/categories/children.png';
  final colleague_png = 'assets/images/categories/colleague.png';
  final father_png = 'assets/images/categories/father.png';
  final friends_png = 'assets/images/categories/friends.png';
  final grandfather_png = 'assets/images/categories/grandfather.png';
  final grandmother_png = 'assets/images/categories/grandmother.png';
  final husband_png = 'assets/images/categories/husband.png';
  final mother_png = 'assets/images/categories/mother.png';
  final uncle_png = 'assets/images/categories/uncle.png';
  final wife_png = 'assets/images/categories/wife.png';
}

class _assets_images_logo_dart {
  final Brightness _brightness;

  _assets_images_logo_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final Wardaya_Application_splash_gif = 'assets/images/logo/Wardaya_Application_splash.gif';
  final loading_gif_gif = 'assets/images/logo/loading_gif.gif';
  final splash_png = 'assets/images/logo/splash.png';
  final splash_android12_logo_png = 'assets/images/logo/splash_android12_logo.png';
  final splash_android12_logo_empty_png = 'assets/images/logo/splash_android12_logo_empty.png';
}

class _assets_lottie_dart {
  final Brightness _brightness;

  _assets_lottie_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final loading_animation_json = 'assets/lottie/loading_animation.json';
}

class _assets_pay_cards_dart {
  final Brightness _brightness;

  _assets_pay_cards_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final gpay_png = 'assets/pay_cards/gpay.png';
  final mada_png = 'assets/pay_cards/mada.png';
  final master_card_png = 'assets/pay_cards/master_card.png';
  final paypal_png = 'assets/pay_cards/paypal.png';
  final tamara_png = 'assets/pay_cards/tamara.png';
  final visa_png = 'assets/pay_cards/visa.png';
}

class _assets_svgs_dart {
  final Brightness _brightness;

  _assets_svgs_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final add_cart_svg = 'assets/svgs/add_cart.svg';
  final addresses_svg = 'assets/svgs/addresses.svg';
  final apple_svg = 'assets/svgs/apple.svg';
  final ballons_svg = 'assets/svgs/ballons.svg';
  final cart_svg = 'assets/svgs/cart.svg';
  final customer_care_svg = 'assets/svgs/customer_care.svg';
  final customize_delivery_svg = 'assets/svgs/customize_delivery.svg';
  final delete_account_svg = 'assets/svgs/delete_account.svg';
  final delivery_svg = 'assets/svgs/delivery.svg';
  final edit_pen_svg = 'assets/svgs/edit_pen.svg';
  final empty_cart_svg = 'assets/svgs/empty_cart.svg';
  final enjoy_fresh_flowers_svg = 'assets/svgs/enjoy_fresh_flowers.svg';
  final explore_svg = 'assets/svgs/explore.svg';
  final faq_svg = 'assets/svgs/faq.svg';
  final fav_gifs_svg = 'assets/svgs/fav_gifs.svg';
  final favs_svg = 'assets/svgs/favs.svg';
  final filter_svg = 'assets/svgs/filter.svg';
  final gift_card_svg = 'assets/svgs/gift_card.svg';
  final google_svg = 'assets/svgs/google.svg';
  final grid_svg = 'assets/svgs/grid.svg';
  final home_svg = 'assets/svgs/home.svg';
  final invoices_svg = 'assets/svgs/invoices.svg';
  final language_svg = 'assets/svgs/language.svg';
  final link_svg = 'assets/svgs/link.svg';
  final location_icon_svg = 'assets/svgs/location_icon.svg';
  final logout_svg = 'assets/svgs/logout.svg';
  final occassions_svg = 'assets/svgs/occassions.svg';
  final orders_truck_svg = 'assets/svgs/orders_truck.svg';
  final phone_svg = 'assets/svgs/phone.svg';
  final points_svg = 'assets/svgs/points.svg';
  final profile_svg = 'assets/svgs/profile.svg';
  final profile_avatar_svg = 'assets/svgs/profile_avatar.svg';
  final remove_svg = 'assets/svgs/remove.svg';
  final select_plan_svg = 'assets/svgs/select_plan.svg';
  final share_svg = 'assets/svgs/share.svg';
  final signature_svg = 'assets/svgs/signature.svg';
  final small_logo_svg = 'assets/svgs/small_logo.svg';
  final subscription_svg = 'assets/svgs/subscription.svg';
  final tac_svg = 'assets/svgs/tac.svg';
  final text_svg = 'assets/svgs/text.svg';
  final tile_svg = 'assets/svgs/tile.svg';
  final video_svg = 'assets/svgs/video.svg';
  final wallet_svg = 'assets/svgs/wallet.svg';
  final wardaya_points_icon_svg = 'assets/svgs/wardaya_points_icon.svg';
  final whatsapp_svg = 'assets/svgs/whatsapp.svg';
}
