import 'package:flutter/material.dart';
import 'package:wardaya/core/assets/assets.dart';

List<String> categoriesImages(BuildContext context) => [
      Assets.of(context).images.ballones_png,
      Assets.of(context).images.cake_png,
      Assets.of(context).images.flower_gift_png,
      Assets.of(context).images.ring_png,
      Assets.of(context).images.teddy_png,
      Assets.of(context).images.ballones_png,
      Assets.of(context).images.cake_png,
      Assets.of(context).images.flower_gift_png,
      Assets.of(context).images.ring_png,
      Assets.of(context).images.teddy_png,
      Assets.of(context).images.teddy_png,
      Assets.of(context).images.flower_gift_png,
      Assets.of(context).images.flower_gift_png,
      Assets.of(context).images.ballones_png,
      Assets.of(context).images.cake_png,
      Assets.of(context).images.flower_gift_png,
      Assets.of(context).images.ring_png,
      Assets.of(context).images.teddy_png,
      Assets.of(context).images.ballones_png,
      Assets.of(context).images.cake_png,
      Assets.of(context).images.flower_gift_png,
      Assets.of(context).images.ring_png,
      Assets.of(context).images.teddy_png,
    ];
final List<String> titles = [
  'ballones',
  'cake',
  'flowers',
  'ring',
  'teddy',
  'ballones',
  'cake',
  'flowers',
  'ring',
  'teddy',
  'teddy',
  'flowers',
  'flowers',
  'ballones',
  'cake',
  'flowers',
  'ring',
  'teddy',
  'ballones',
  'cake',
  'flowers',
  'ring',
  'teddy',
];
List<String> giftsCategoriesImages(BuildContext context) => [
      Assets.of(context).images.categories.friends_png,
      Assets.of(context).images.categories.colleague_png,
      Assets.of(context).images.categories.mother_png,
      Assets.of(context).images.categories.friends_png,
      Assets.of(context).images.categories.colleague_png,
      Assets.of(context).images.categories.mother_png,
      Assets.of(context).images.categories.wife_png,
      Assets.of(context).images.categories.husband_png,
      Assets.of(context).images.categories.father_png,
      Assets.of(context).images.categories.wife_png,
      Assets.of(context).images.categories.husband_png,
      Assets.of(context).images.categories.father_png,
    ];
final List<String> giftsTitles = [
  'friends',
  'colleague',
  'mother',
  'friends',
  'colleague',
  'mother',
  'wife',
  'husband',
  'father',
  'wife',
  'husband',
  'father',
];
final List<String> brandsCategoriesImages = [
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
];
final List<String> brandsTitles = [
  'Mubkhar',
  'Hanoverian',
  'Damas',
  'Mubkhar',
  'Hanoverian',
  'Damas',
  'Hanoverian',
  'Levo',
  'September Studio',
  'Damas',
  'Levo',
  'September Studio',
];
final List<String> names = [
  'Unique Red Flowers Box',
  'Blushing Elegance Box',
  'White Roses Box',
  'Romantic Flowers Box',
];

final List<int> prices = [
  489,
  750,
  409,
  409,
];
final List<String> recipients = [
  "Mother",
  "Father",
  "Children",
  "Husband",
  "Wife",
  "Grandmother",
  "Grandfather",
  "Aunt",
  "Uncle",
  "Friends",
  "Colleagues",
];
List<String> recipientsImages(BuildContext context) => [
      Assets.of(context).images.categories.mother_png,
      Assets.of(context).images.categories.father_png,
      Assets.of(context).images.categories.children_png,
      Assets.of(context).images.categories.husband_png,
      Assets.of(context).images.categories.wife_png,
      Assets.of(context).images.categories.grandmother_png,
      Assets.of(context).images.categories.grandfather_png,
      Assets.of(context).images.categories.friends_png,
      Assets.of(context).images.categories.aunt_png,
      Assets.of(context).images.categories.uncle_png,
      Assets.of(context).images.categories.colleague_png,
    ];

class Product {
  final String name;
  final double price;
  final String imageUrl;
  final String category;
  final String occasion;
  final String recipient;
  final String color;

  Product(
      {required this.name,
      required this.price,
      required this.imageUrl,
      required this.category,
      required this.occasion,
      required this.recipient,
      required this.color});
}

List<Product> allProducts = [
  Product(
      name: "Helen's Happy Birthday Drawing Cake",
      price: 200,
      imageUrl: "",
      category: "Cakes",
      occasion: "Birthday",
      recipient: "Adult",
      color: "Multi"),
  Product(
      name: "Elegant Rose Bouquet",
      price: 150,
      imageUrl: "",
      category: "Flowers",
      occasion: "Anniversary",
      recipient: "Partner",
      color: "Red"),
  Product(
      name: "Birthday Chocolate Cake",
      price: 180,
      imageUrl: "",
      category: "Cakes",
      occasion: "Birthday",
      recipient: "Child",
      color: "Brown"),
  Product(
      name: "Mixed Flower Arrangement",
      price: 220,
      imageUrl: "",
      category: "Flowers",
      occasion: "General",
      recipient: "Parent",
      color: "Multi"),
  Product(
      name: "Simple Birthday Cake",
      price: 200,
      imageUrl: "",
      category: "Cakes",
      occasion: "Birthday",
      recipient: "Friend",
      color: "White"),
  Product(
      name: "Chocolate Sweet Box",
      price: 120,
      imageUrl: "",
      category: "Sweets & Chocolate",
      occasion: "General",
      recipient: "Friend",
      color: "Brown"),
  Product(
      name: "Golden Necklace",
      price: 300,
      imageUrl: "",
      category: "Jewelry",
      occasion: "Anniversary",
      recipient: "Partner",
      color: "Gold"),
  Product(
      name: "Classic Perfume",
      price: 250,
      imageUrl: "",
      category: "Perfumes",
      occasion: "Birthday",
      recipient: "Adult",
      color: "None"),
  Product(
      name: "Gift Card",
      price: 50,
      imageUrl: "",
      category: "Vouchers",
      occasion: "General",
      recipient: "Any",
      color: "None"),
  Product(
      name: "Delicious Donut Box",
      price: 90,
      imageUrl: "",
      category: "Sweets & Chocolate",
      occasion: "General",
      recipient: "Friend",
      color: "Multi"),
  Product(
      name: "Silver Ring",
      price: 120,
      imageUrl: "",
      category: "Jewelry",
      occasion: "Anniversary",
      recipient: "Partner",
      color: "Silver"),
  Product(
      name: "Elegant Woman Perfume",
      price: 350,
      imageUrl: "",
      category: "Perfumes",
      occasion: "Birthday",
      recipient: "Adult",
      color: "None"),
];
