final List<String> categoriesImages = [
  'assets/images/ballones.png',
  'assets/images/cake.png',
  'assets/images/flower_gift.png',
  'assets/images/ring.png',
  'assets/images/teddy.png',
  'assets/images/ballones.png',
  'assets/images/cake.png',
  'assets/images/flower_gift.png',
  'assets/images/ring.png',
  'assets/images/teddy.png',
  'assets/images/teddy.png',
  'assets/images/flower_gift.png',
  'assets/images/flower_gift.png',
  'assets/images/ballones.png',
  'assets/images/cake.png',
  'assets/images/flower_gift.png',
  'assets/images/ring.png',
  'assets/images/teddy.png',
  'assets/images/ballones.png',
  'assets/images/cake.png',
  'assets/images/flower_gift.png',
  'assets/images/ring.png',
  'assets/images/teddy.png',
];
final List<String> titles = [
  'ballones',
  'cake',
  'flowers',
  'ring',
  'teddy',
  'ballones',
  'cake',
  'flowers',
  'ring',
  'teddy',
  'teddy',
  'flowers',
  'flowers',
  'ballones',
  'cake',
  'flowers',
  'ring',
  'teddy',
  'ballones',
  'cake',
  'flowers',
  'ring',
  'teddy',
];
final List<String> giftsCategoriesImages = [
  'assets/images/categories/friends.png',
  'assets/images/categories/colleague.png',
  'assets/images/categories/mother.png',
  'assets/images/categories/friends.png',
  'assets/images/categories/colleague.png',
  'assets/images/categories/mother.png',
  'assets/images/categories/wife.png',
  'assets/images/categories/husband.png',
  'assets/images/categories/father.png',
  'assets/images/categories/wife.png',
  'assets/images/categories/husband.png',
  'assets/images/categories/father.png',
];
final List<String> giftsTitles = [
  'friends',
  'colleague',
  'mother',
  'friends',
  'colleague',
  'mother',
  'wife',
  'husband',
  'father',
  'wife',
  'husband',
  'father',
];
final List<String> brandsCategoriesImages = [
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
];
final List<String> brandsTitles = [
  'Mubkhar',
  'Hanoverian',
  'Damas',
  'Mubkhar',
  'Hanoverian',
  'Damas',
  'Hanoverian',
  'Levo',
  'September Studio',
  'Damas',
  'Levo',
  'September Studio',
];
final List<String> names = [
  'Unique Red Flowers Box',
  'Blushing Elegance Box',
  'White Roses Box',
  'Romantic Flowers Box',
];

final List<int> prices = [
  489,
  750,
  409,
  409,
];
